"""Initial migration.

Revision ID: fe6904d130d9
Revises: 
Create Date: 2024-03-07 01:29:01.578914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6904d130d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('npi_number', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi_number')
    )
    with op.batch_alter_table('clinician', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinician_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinician_last_name'), ['last_name'], unique=False)

    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_last_name'), ['last_name'], unique=False)

    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_last_name'))
        batch_op.drop_index(batch_op.f('ix_patient_first_name'))

    op.drop_table('patient')
    with op.batch_alter_table('clinician', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinician_last_name'))
        batch_op.drop_index(batch_op.f('ix_clinician_first_name'))

    op.drop_table('clinician')
    # ### end Alembic commands ###
